server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Отдаём сжатые файлы если есть
    gzip_static on;

    # SPA — все неизвестные пути → index.html (React Router)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Кэширование статики (js, css, картинки)
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|webp|woff2?)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}
